# Generated by Django 4.0.4 on 2022-05-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventDay',
            field=models.DateField(null=True),
        ),
    ]
